include:
    # Metadata shared my many jobs
    - local: .gitlab/rules.yml
    - local: .gitlab/artifacts.yml
    - local: .gitlab/warning-policy.yml

    # OS builds.
    - local: .gitlab/os-linux.yml
    - local: .gitlab/os-windows.yml

stages:
    - build
    - test

################################################################################
# Job declarations
#
# Each job must pull in each of the following keys:
#
#   - a "base image"
#   - a build script
#   - tags for the jobs
#     - already provided for upload and CI update jobs
#   - rules for when to run the job
#
# Additionally, jobs may also contain:
#
#   - artifacts
#   - dependency/needs jobs for required jobs
################################################################################

# Linux

## Basic builds

ubuntu2004-arrows:build:
    extends:
        - .ubuntu2004_arrows
        - .cmake_build_linux
        - .linux_builder_tags
        - .cmake_build_artifacts
        - .rules

ubuntu2004-arrows:test:
    extends:
        - .ubuntu2004_arrows
        - .cmake_test_linux
        - .linux_tester_tags
        - .cmake_test_artifacts
        - .rules
    variables:
        RUN_DEPENDENT: "true"
    dependencies:
        - ubuntu2004-arrows:build
    needs:
        - ubuntu2004-arrows:build

# linux python wheels
wheel-linux-python38-x86_64:build:
    extends:
        - .wheel_linux38_x86_64
        - .cmake_build_wheel_linux
        - .linux_builder_tags
        - .cmake_wheel_artifacts
        - .rules

wheel-linux-python38-x86_64:test:
    extends:
        - .test_wheel_linux38_x86_64
        - .cmake_test_wheel_linux
        - .linux_tester_tags
        - .cmake_wheel_artifacts
        - .rules
    variables:
        RUN_DEPENDENT: "true"
    dependencies:
        - wheel-linux-python38-x86_64:build
    needs:
        - wheel-linux-python38-x86_64:build

wheel-linux-python38-x86_64_burnout:build:
    extends:
        - .wheel_linux38_x86_64_burnout
        - .cmake_build_wheel_linux
        - .linux_builder_tags
        - .cmake_wheel_artifacts
        - .rules

wheel-linux-python38-x86_64_burnout:test:
    extends:
        - .test_wheel_linux38_x86_64
        - .cmake_test_burnout_wheel_linux
        - .linux_tester_tags
        - .cmake_wheel_artifacts
        - .rules
    variables:
        RUN_DEPENDENT: "true"
    dependencies:
        - wheel-linux-python38-x86_64:build
    needs:
        - wheel-linux-python38-x86_64:build

# Windows

## Basic builds

windows-vs2022-ninja-arrows:build:
    extends:
        - .windows_vs2022_ninja_arrows
        - .cmake_build_windows
        - .windows_builder_tags
        - .cmake_build_artifacts
        - .rules

windows-vs2022-ninja-arrows:test:
    extends:
        - .windows_vs2022_ninja_arrows
        - .cmake_test_windows
        - .windows_builder_tags
        - .cmake_test_artifacts
        - .rules
    variables:
        RUN_DEPENDENT: "true"
    dependencies:
        - windows-vs2022-ninja-arrows:build
    needs:
        - windows-vs2022-ninja-arrows:build

# windows wheels
wheel-windows-python38-x86_64:build:
    extends:
        - .wheel_windows38_x86_64
        - .cmake_build_wheel_windows
        - .windows_builder_tags
        - .cmake_wheel_artifacts
        - .rules

wheel-windows-python38-x86_64:test:
    extends:
        - .wheel_windows38_x86_64
        - .cmake_test_wheel_windows
        - .windows_builder_tags
        - .cmake_wheel_artifacts
        - .rules
    variables:
        RUN_DEPENDENT: "true"
    dependencies:
        - wheel-windows-python38-x86_64:build
    needs:
        - wheel-windows-python38-x86_64:build

wheel-windows-python38-x86_64_burnout:build:
    extends:
        - .wheel_windows38_x86_64_burnout
        - .cmake_build_wheel_windows
        - .windows_builder_tags
        - .cmake_wheel_artifacts
        - .rules
