include:
    # Metadata shared my many jobs
    - local: .gitlab/rules.yml
    - local: .gitlab/artifacts.yml
    - local: .gitlab/warning-policy.yml

    # OS builds.
    - local: .gitlab/os-linux.yml

stages:
    - build
    - test

################################################################################
# Job declarations
#
# Each job must pull in each of the following keys:
#
#   - a "base image"
#   - a build script
#   - tags for the jobs
#     - already provided for upload and CI update jobs
#   - rules for when to run the job
#
# Additionally, jobs may also contain:
#
#   - artifacts
#   - dependency/needs jobs for required jobs
################################################################################

# Linux

## Basic builds

ubuntu2004-ffmpeg-gdal-opencv-proj-python:build:
    extends:
        - .ubuntu2004_ffmpeg_gdal_opencv_proj_python
        - .cmake_build_linux
        - .linux_builder_tags
        - .cmake_build_artifacts
        - .rules

ubuntu2004-ffmpeg-gdal-opencv-proj-python:test:
    extends:
        - .ubuntu2004_ffmpeg_gdal_opencv_proj_python
        - .cmake_test_linux
        - .linux_tester_tags
        - .cmake_test_artifacts
        - .rules
    variables:
        RUN_DEPENDENT: "true"
    dependencies:
        - ubuntu2004-ffmpeg-gdal-opencv-proj-python:build
    needs:
        - ubuntu2004-ffmpeg-gdal-opencv-proj-python:build
