# Default to Debug builds.
if ("$ENV{CMAKE_BUILD_TYPE}" STREQUAL "")
  set(CMAKE_BUILD_TYPE "Debug" CACHE STRING "")
else ()
  set(CMAKE_BUILD_TYPE "$ENV{CMAKE_BUILD_TYPE}" CACHE STRING "")
endif ()

include("${CMAKE_CURRENT_LIST_DIR}/configure_cache.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/configure_options.cmake")

# Stock options.
set(KWIVER_ENABLE_TESTS ON CACHE BOOL "")
set(KWIVER_ENABLE_ARROWS ON CACHE BOOL "")
set(KWIVER_ENABLE_TOOLS ON CACHE BOOL "")

# Arrows
set(KWIVER_ENABLE_GDAL ON CACHE BOOL "")
set(KWIVER_ENABLE_KLV ON CACHE BOOL "")
set(KWIVER_ENABLE_MVG ON CACHE BOOL "")
set(KWIVER_ENABLE_PROJ ON CACHE BOOL "")
set(KWIVER_ENABLE_SERIALIZE_JSON ON CACHE BOOL "")
set(KWIVER_ENABLE_ZLIB ON CACHE BOOL "")
