# Default to Debug builds.
if ("$ENV{CMAKE_BUILD_TYPE}" STREQUAL "")
  set(CMAKE_BUILD_TYPE "Debug" CACHE STRING "")
else ()
  set(CMAKE_BUILD_TYPE "$ENV{CMAKE_BUILD_TYPE}" CACHE STRING "")
endif ()

set(KWIVER_ENABLE_C_BINDINGS ON CACHE BOOL "")
set(KWIVER_ENABLE_PYTHON ON CACHE BOOL "")
set(KWIVER_ENABLE_TOOLS ON CACHE BOOL "")
set(KWIVER_ENABLE_TESTS ON CACHE BOOL "")
set(KWIVER_ENABLE_ARROWS ON CACHE BOOL "")
# arrows
set(KWIVER_ENABLE_DBOW2 OFF CACHE BOOL "")
set(KWIVER_ENABLE_KLV ON CACHE BOOL "")
set(KWIVER_ENABLE_MVG ON CACHE BOOL "")
set(KWIVER_ENABLE_OPENCV ON CACHE BOOL "")
set(KWIVER_ENABLE_SERIALIZE_JSON ON CACHE BOOL "")
